[package]
name = "illuvi-analytics-ui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "illuvi-analytics-ui"
path = "src/main.rs"

[dependencies]
model = { path= "../model"}
log = "0.4.6"
wasm-logger = "0.2.0"
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17"
reqwest = { version = "0.11", features = ["json"] }
wasm-bindgen-futures = "0.4.34"
serde = { version = "1.0.159", features = ["derive"] }
