[package]
name = "illuvi-analytics-ui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "illuvi-analytics-ui"
path = "src/main.rs"

[dependencies]
model = { path= "../model"}
log = "0.4.18"
wasm-logger = "0.2.0"
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17"
reqwest = { version = "0.11.18", features = ["json"] }
wasm-bindgen-futures = "0.4.36"
serde = { version = "1.0.163", features = ["derive"] }
chrono = { version = "0.4.24", features = ["serde"] }
dotenvy_macro = "0.15.7"
web-sys = { version = "0.3.63", features = ["Window", "ScrollToOptions", "ScrollBehavior"] }