version: "3"
services:
  db:
    image: postgres:15.3
    shm_size: 1g
    command: -c max_connections=200 -c shared_buffers=2GB -c effective_cache_size=4GB -c work_mem=128MB
    restart: 'no'
    environment:
      POSTGRES_PASSWORD: notsecure
      POSTGRES_USER: data-loader-local
      POSTGRES_DB: illuvium-land
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9.19.1
    command: -url=jdbc:postgresql://db/illuvium-land -schemas=public -user=data-loader-local -password=notsecure -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

volumes:
  postgres_data: {}